-- Banco de Dados para o Show do Milhão
-- 300 questões (100 fáceis, 100 médias, 100 difíceis)

CREATE TABLE questoes_show_do_milhao (
    id INT PRIMARY KEY,
    pergunta VARCHAR(255) NOT NULL,
    alternativa_a VARCHAR(100) NOT NULL,
    alternativa_b VARCHAR(100) NOT NULL,
    alternativa_c VARCHAR(100) NOT NULL,
    alternativa_d VARCHAR(100) NOT NULL,
    correta CHAR(1) NOT NULL,
    dificuldade VARCHAR(10) NOT NULL,
    categoria VARCHAR(50) NOT NULL
);

-- Questões Fáceis (1-100)
INSERT INTO questoes_show_do_milhao VALUES
(1, 'Qual é a capital do Brasil?', 'Rio de Janeiro', 'São Paulo', 'Brasília', 'Belo Horizonte', 'C', 'fácil', 'Geografia'),
(2, 'Quantos planetas existem no sistema solar?', '7', '8', '9', '10', 'B', 'fácil', 'Ciência'),
(3, 'Qual é o maior osso do corpo humano?', 'Fêmur', 'Tíbia', 'Úmero', 'Costela', 'A', 'fácil', 'Biologia'),
(4, 'Qual é o nome do dragão de "Como Treinar o Seu Dragão"?', 'Banguela', 'Smaug', 'Toothless', 'Fúria da Noite', 'C', 'fácil', 'Entretenimento'),
(5, 'Qual filme da Disney tem a música "Let It Go"?', 'Moana', 'Frozen', 'Encanto', 'A Bela e a Fera', 'B', 'fácil', 'Entretenimento'),
(6, 'Quem interpreta o Homem de Ferro nos filmes da Marvel?', 'Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo', 'B', 'fácil', 'Entretenimento'),
(7, 'Qual destes NÃO é um filme da Pixar?', 'Toy Story', 'Shrek', 'Procurando Nemo', 'Carros', 'B', 'fácil', 'Entretenimento'),
(8, 'Qual é o nome do vilão em "O Rei Leão"?', 'Zazu', 'Scar', 'Mufasa', 'Timão', 'B', 'fácil', 'Entretenimento'),
(9, 'Em que filme aparece o personagem Jack Sparrow?', 'Piratas do Caribe', 'Titanic', 'Gladiador', 'O Senhor dos Anéis', 'A', 'fácil', 'Entretenimento'),
(10, 'Qual destes é um filme da saga "Harry Potter"?', 'O Hobbit', 'As Crônicas de Nárnia', 'A Pedra Filosofal', 'Percy Jackson', 'C', 'fácil', 'Entretenimento'),
(11, 'Qual é o nome do robô em "Wall-E"?', 'EVA', 'R2-D2', 'BB-8', 'Optimus Prime', 'A', 'fácil', 'Entretenimento'),
(12, 'Qual atriz interpreta a Rainha Elsa em "Frozen"?', 'Kristen Bell', 'Idina Menzel', 'Demi Lovato', 'Ariana Grande', 'B', 'fácil', 'Entretenimento'),
(13, 'Qual destes filmes é sobre super-heróis?', 'Velozes e Furiosos', 'Homem-Aranha', 'Jurassic Park', 'O Sexto Sentido', 'B', 'fácil', 'Entretenimento'),
(14, 'Qual é o nome do cachorro em "Up - Altas Aventuras"?', 'Dug', 'Max', 'Scooby', 'Pluto', 'A', 'fácil', 'Entretenimento'),
(15, 'Qual filme tem os personagens Woody e Buzz?', 'Carros', 'Toy Story', 'Monstros S.A.', 'Os Incríveis', 'B', 'fácil', 'Entretenimento'),
(16, 'Qual destes filmes é da Disney?', 'Shrek', 'Madagascar', 'A Pequena Sereia', 'Kung Fu Panda', 'C', 'fácil', 'Entretenimento'),
(17, 'Qual é o nome do vilão em "Moana"?', 'Maui', 'Tamatoa', 'Te Kā', 'Heihei', 'C', 'fácil', 'Entretenimento'),
(18, 'Qual ator interpreta o Capitão América nos filmes?', 'Chris Pratt', 'Chris Pine', 'Chris Evans', 'Chris Hemsworth', 'C', 'fácil', 'Entretenimento'),
(19, 'Qual filme tem a música "Hakuna Matata"?', 'Aladdin', 'Mulan', 'O Rei Leão', 'A Bela e a Fera', 'C', 'fácil', 'Entretenimento'),
(20, 'Qual destes filmes é sobre carros de corrida?', 'Carros', 'Aviões', 'Táxi', 'Velozes e Furiosos', 'A', 'fácil', 'Entretenimento'),
(21, 'Qual é o nome do gato em "Shrek"?', 'Garfield', 'Gato de Botas', 'Tom', 'Felix', 'B', 'fácil', 'Entretenimento'),
(22, 'Qual filme tem o personagem Dory?', 'Procurando Nemo', 'Vida de Inseto', 'Os Incríveis', 'Ratatouille', 'A', 'fácil', 'Entretenimento'),
(23, 'Qual destes filmes é sobre um ratinho que cozinha?', 'Ratatouille', 'Madagascar', 'Zootopia', 'Frozen', 'A', 'fácil', 'Entretenimento'),
(24, 'Qual é a cor da neve?', 'Preta', 'Azul', 'Branca', 'Verde', 'C', 'fácil', 'Conhecimentos Gerais'),
(25, 'Qual destes é um planeta?', 'Lua', 'Sol', 'Marte', 'Satélite', 'C', 'fácil', 'Ciência'),
(26, 'Quantos continentes existem?', '5', '6', '7', '8', 'B', 'fácil', 'Geografia'),
(27, 'Qual é a capital do Rio Grande do Sul?', 'Curitiba', 'Florianópolis', 'Porto Alegre', 'São Paulo', 'C', 'fácil', 'Geografia'),
(28, 'Qual destes é um vegetal?', 'Frango', 'Peixe', 'Cenoura', 'Leite', 'C', 'fácil', 'Conhecimentos Gerais'),
(29, 'Qual é a moeda do Brasil?', 'Dólar', 'Euro', 'Real', 'Peso', 'C', 'fácil', 'Economia'),
(30, 'Quantos times jogam em uma partida de futebol?', '1', '2', '3', '4', 'B', 'fácil', 'Esportes'),
(31, 'Qual destes é um instrumento musical?', 'Martelo', 'Violão', 'Serra', 'Furadeira', 'B', 'fácil', 'Música'),
(32, 'Qual é a cor do sol?', 'Azul', 'Verde', 'Amarelo', 'Vermelho', 'C', 'fácil', 'Ciência'),
(33, 'Quantas pernas tem uma cadeira comum?', '1', '2', '3', '4', 'D', 'fácil', 'Conhecimentos Gerais'),
(34, 'Qual destes é um país?', 'Amazonas', 'Brasília', 'Canadá', 'Rio de Janeiro', 'C', 'fácil', 'Geografia'),
(35, 'Qual é o oposto de dia?', 'Tarde', 'Noite', 'Manhã', 'Anoitecer', 'B', 'fácil', 'Conhecimentos Gerais'),
(36, 'Quantas notas musicais existem?', '5', '7', '9', '12', 'B', 'fácil', 'Música'),
(37, 'Qual destes é um líquido?', 'Pedra', 'Água', 'Madeira', 'Ferro', 'B', 'fácil', 'Ciência'),
(38, 'Qual é a capital dos Estados Unidos?', 'Nova York', 'Los Angeles', 'Washington', 'Chicago', 'C', 'fácil', 'Geografia'),
(39, 'Quantos dedos tem uma mão humana?', '3', '4', '5', '6', 'C', 'fácil', 'Biologia'),
(40, 'Qual destes é um doce brasileiro?', 'Pizza', 'Brigadeiro', 'Sushi', 'Hambúrguer', 'B', 'fácil', 'Cultura'),
(41, 'Qual é o maior mamífero do mundo?', 'Elefante', 'Girafa', 'Baleia-azul', 'Rinoceronte', 'C', 'fácil', 'Biologia'),
(42, 'Quantos minutos tem uma hora?', '30', '60', '90', '100', 'B', 'fácil', 'Conhecimentos Gerais'),
(43, 'Qual destes é um esporte olímpico?', 'Xadrez', 'Natação', 'Dominó', 'Sinuca', 'B', 'fácil', 'Esportes'),
(44, 'Qual é a cor do semáforo que significa "pare"?', 'Verde', 'Amarelo', 'Vermelho', 'Azul', 'C', 'fácil', 'Conhecimentos Gerais'),
(45, 'Qual destes é um país da Europa?', 'Canadá', 'Brasil', 'França', 'Japão', 'C', 'fácil', 'Geografia'),
(46, 'Quantas estrelas tem a bandeira do Brasil?', '23', '26', '27', '30', 'C', 'fácil', 'Conhecimentos Gerais'),
(47, 'Qual é a capital da Itália?', 'Milão', 'Veneza', 'Roma', 'Florença', 'C', 'fácil', 'Geografia'),
(48, 'Qual destes é um filme da Disney?', 'Titanic', 'Branca de Neve', 'O Poderoso Chefão', 'Matrix', 'B', 'fácil', 'Entretenimento'),
(49, 'Qual é o símbolo químico do hidrogênio?', 'Hd', 'He', 'H', 'Hi', 'C', 'fácil', 'Ciência'),
(50, 'Quantas teclas tem um piano tradicional?', '56', '72', '88', '104', 'C', 'fácil', 'Música'),
(51, 'Qual destes é um estado brasileiro?', 'Buenos Aires', 'Montevidéu', 'São Paulo', 'Lima', 'C', 'fácil', 'Geografia'),
(52, 'Qual é o resultado de 10-5?', '2', '5', '7', '10', 'B', 'fácil', 'Matemática'),
(53, 'Quantos jogadores tem um time de futebol?', '9', '10', '11', '12', 'C', 'fácil', 'Esportes'),
(54, 'Qual destes é um inseto?', 'Cachorro', 'Gato', 'Formiga', 'Cobra', 'C', 'fácil', 'Biologia'),
(55, 'Qual é a capital do Japão?', 'Pequim', 'Seul', 'Tóquio', 'Bangkok', 'C', 'fácil', 'Geografia'),
(56, 'Quantas cores tem o arco-íris?', '5', '6', '7', '8', 'C', 'fácil', 'Ciência'),
(57, 'Qual destes é um cereal?', 'Batata', 'Arroz', 'Cenoura', 'Tomate', 'B', 'fácil', 'Conhecimentos Gerais'),
(58, 'Qual é o maior órgão do corpo humano?', 'Coração', 'Cérebro', 'Pele', 'Fígado', 'C', 'fácil', 'Biologia'),
(59, 'Quantos zeros tem o número mil?', '1', '2', '3', '4', 'C', 'fácil', 'Matemática'),
(60, 'Qual destes é um instrumento de percussão?', 'Violino', 'Trompete', 'Bateria', 'Flauta', 'C', 'fácil', 'Música'),
(61, 'Qual é a capital da Bahia?', 'Recife', 'Fortaleza', 'Salvador', 'Natal', 'C', 'fácil', 'Geografia'),
(62, 'Qual é o resultado de 5x5?', '10', '15', '20', '25', 'D', 'fácil', 'Matemática'),
(63, 'Quantos ossos tem o corpo humano?', '106', '206', '306', '406', 'B', 'fácil', 'Biologia'),
(64, 'Qual destes é um filme de super-herói?', 'Titanic', 'Homem-Aranha', 'O Rei Leão', 'Toy Story', 'B', 'fácil', 'Entretenimento'),
(65, 'Qual é a capital de Portugal?', 'Madri', 'Barcelona', 'Lisboa', 'Porto', 'C', 'fácil', 'Geografia'),
(66, 'Quantas sílabas tem a palavra "casa"?', '1', '2', '3', '4', 'B', 'fácil', 'Português'),
(67, 'Qual destes é um refrigerante?', 'Suco de laranja', 'Água', 'Coca-Cola', 'Leite', 'C', 'fácil', 'Conhecimentos Gerais'),
(68, 'Qual é o símbolo químico do carbono?', 'Ca', 'Cb', 'C', 'Co', 'C', 'fácil', 'Ciência'),
(69, 'Quantos lados tem um quadrado?', '2', '3', '4', '5', 'C', 'fácil', 'Matemática'),
(70, 'Qual destes é um país da América do Sul?', 'Canadá', 'México', 'Argentina', 'Estados Unidos', 'C', 'fácil', 'Geografia'),
(71, 'Qual é a capital de Santa Catarina?', 'Porto Alegre', 'Curitiba', 'Florianópolis', 'São Paulo', 'C', 'fácil', 'Geografia'),
(72, 'Quantos anos tem um século?', '10', '50', '100', '200', 'C', 'fácil', 'Conhecimentos Gerais'),
(73, 'Qual destes é um animal doméstico?', 'Leão', 'Tigre', 'Cachorro', 'Elefante', 'C', 'fácil', 'Biologia'),
(74, 'Qual é o resultado de 100÷10?', '1', '5', '10', '20', 'C', 'fácil', 'Matemática'),
(75, 'Quantos estados tem o Brasil?', '23', '26', '27', '30', 'B', 'fácil', 'Geografia'),
(76, 'Qual destes é um metal precioso?', 'Plástico', 'Madeira', 'Ouro', 'Vidro', 'C', 'fácil', 'Ciência'),
(77, 'Qual é a capital de Pernambuco?', 'Maceió', 'Recife', 'Salvador', 'Fortaleza', 'B', 'fácil', 'Geografia'),
(78, 'Quantas letras tem o alfabeto português?', '23', '24', '25', '26', 'D', 'fácil', 'Português'),
(79, 'Qual destes é um doce de festa junina?', 'Pizza', 'Pamonha', 'Hambúrguer', 'Sushi', 'B', 'fácil', 'Cultura'),
(80, 'Qual é o símbolo químico do sódio?', 'So', 'Sd', 'Na', 'No', 'C', 'fácil', 'Ciência'),
(81, 'Quantas semanas tem um mês?', '2', '3', '4', '5', 'C', 'fácil', 'Conhecimentos Gerais'),
(82, 'Qual destes é um esporte de inverno?', 'Futebol', 'Vôlei', 'Esqui', 'Natação', 'C', 'fácil', 'Esportes'),
(83, 'Qual é a capital do Ceará?', 'Natal', 'João Pessoa', 'Fortaleza', 'Maceió', 'C', 'fácil', 'Geografia'),
(84, 'Quantos quartos tem uma casa comum?', '1', '2', '3', '4', 'B', 'fácil', 'Conhecimentos Gerais'),
(85, 'Qual destes é um fruto?', 'Cenoura', 'Batata', 'Maçã', 'Alface', 'C', 'fácil', 'Conhecimentos Gerais'),
(86, 'Qual é o resultado de 3+7?', '5', '10', '12', '15', 'B', 'fácil', 'Matemática'),
(87, 'Quantos satélites naturais a Terra tem?', '0', '1', '2', '3', 'B', 'fácil', 'Ciência'),
(88, 'Qual destes é um instrumento de sopro?', 'Violão', 'Bateria', 'Flauta', 'Piano', 'C', 'fácil', 'Música'),
(89, 'Qual é a capital do Amazonas?', 'Belém', 'Manaus', 'Porto Velho', 'Macapá', 'B', 'fácil', 'Geografia'),
(90, 'Quantos times participam da Copa do Mundo?', '16', '24', '32', '40', 'C', 'fácil', 'Esportes'),
(91, 'Qual destes é um país africano?', 'Canadá', 'Egito', 'China', 'Austrália', 'B', 'fácil', 'Geografia'),
(92, 'Qual é o resultado de 8÷2?', '2', '3', '4', '5', 'C', 'fácil', 'Matemática'),
(93, 'Quantas patas tem um cachorro?', '2', '3', '4', '5', 'C', 'fácil', 'Biologia'),
(94, 'Qual destes é um personagem da Turma da Mônica?', 'Batman', 'Cebolinha', 'Homem-Aranha', 'Mickey', 'B', 'fácil', 'Entretenimento'),
(95, 'Qual é a capital do Rio de Janeiro?', 'São Paulo', 'Belo Horizonte', 'Rio de Janeiro', 'Vitória', 'C', 'fácil', 'Geografia'),
(96, 'Quantas notas musicais existem na escala diatônica?', '5', '7', '9', '12', 'B', 'fácil', 'Música'),
(97, 'Qual destes é um tipo de nuvem?', 'Cúmulo', 'Granito', 'Basalto', 'Arenito', 'A', 'fácil', 'Ciência'),
(98, 'Qual é o resultado de 6x6?', '12', '24', '36', '48', 'C', 'fácil', 'Matemática'),
(99, 'Quantos lados tem um pentágono?', '3', '4', '5', '6', 'C', 'fácil', 'Matemática'),
(100, 'Qual destes é um filme de animação?', 'O Poderoso Chefão', 'Os Incríveis', 'Titanic', 'Matrix', 'B', 'fácil', 'Entretenimento');

-- Questões Médias (101-200)
INSERT INTO questoes_show_do_milhao VALUES
(101, 'Quem pintou a Mona Lisa?', 'Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Michelangelo', 'C', 'médio', 'Arte'),
(102, 'Qual elemento químico tem o símbolo "Au"?', 'Prata', 'Mercúrio', 'Ouro', 'Alumínio', 'C', 'médio', 'Ciência'),
(103, 'Em que ano o homem pisou na Lua pela primeira vez?', '1965', '1969', '1972', '1975', 'B', 'médio', 'História'),
(104, 'Quem escreveu "Dom Quixote"?', 'Gabriel García Márquez', 'Miguel de Cervantes', 'Pablo Neruda', 'Jorge Luis Borges', 'B', 'médio', 'Literatura'),
(105, 'Qual destes países não faz parte da União Europeia?', 'França', 'Noruega', 'Alemanha', 'Itália', 'B', 'médio', 'Política'),
(106, 'Qual é a capital da Austrália?', 'Sydney', 'Melbourne', 'Canberra', 'Perth', 'C', 'médio', 'Geografia'),
(107, 'Quantas cordas tem um violão tradicional?', '4', '5', '6', '7', 'C', 'médio', 'Música'),
(108, 'Qual destes não é um osso do crânio humano?', 'Frontal', 'Temporal', 'Fêmur', 'Occipital', 'C', 'médio', 'Biologia'),
(109, 'Em que ano começou a Segunda Guerra Mundial?', '1914', '1939', '1941', '1945', 'B', 'médio', 'História'),
(110, 'Qual é o maior planeta do sistema solar?', 'Terra', 'Marte', 'Júpiter', 'Saturno', 'C', 'médio', 'Ciência'),
(111, 'Qual é a fórmula química da água?', 'HO', 'H2O', 'H2O2', 'HO2', 'B', 'médio', 'Ciência'),
(112, 'Quem foi o primeiro presidente do Brasil após a ditadura militar?', 'Tancredo Neves', 'José Sarney', 'Fernando Collor', 'Itamar Franco', 'A', 'médio', 'História'),
(113, 'Qual destes compositores é brasileiro?', 'Mozart', 'Chopin', 'Villa-Lobos', 'Tchaikovsky', 'C', 'médio', 'Música'),
(114, 'Em que ano o Brasil foi descoberto pelos portugueses?', '1400', '1492', '1500', '1520', 'C', 'médio', 'História'),
(115, 'Qual é o metal mais condutor de eletricidade?', 'Ferro', 'Alumínio', 'Cobre', 'Ouro', 'C', 'médio', 'Ciência'),
(116, 'Quantas vértebras tem a coluna vertebral humana?', '12', '24', '33', '40', 'C', 'médio', 'Biologia'),
(117, 'Qual destes não é um país da América do Sul?', 'Chile', 'Equador', 'México', 'Colômbia', 'C', 'médio', 'Geografia'),
(118, 'Quem escreveu "O Pequeno Príncipe"?', 'Júlio Verne', 'Antoine de Saint-Exupéry', 'Machado de Assis', 'Victor Hugo', 'B', 'médio', 'Literatura'),
(119, 'Qual é o maior deserto do mundo?', 'Deserto do Saara', 'Deserto de Atacama', 'Deserto da Arábia', 'Deserto de Gobi', 'A', 'médio', 'Geografia'),
(120, 'Quantos signos tem o zodíaco?', '10', '12', '14', '16', 'B', 'médio', 'Conhecimentos Gerais'),
(121, 'Qual destes pintores é famoso por seus quadros cubistas?', 'Van Gogh', 'Monet', 'Picasso', 'Da Vinci', 'C', 'médio', 'Arte'),
(122, 'Em que ano foi abolida a escravidão no Brasil?', '1850', '1888', '1900', '1920', 'B', 'médio', 'História'),
(123, 'Qual é o país com maior população do mundo?', 'Estados Unidos', 'Índia', 'China', 'Brasil', 'C', 'médio', 'Geografia'),
(124, 'Quantos anos durou a Guerra Fria?', '20', '30', '40', '50', 'C', 'médio', 'História'),
(125, 'Qual destes não é um órgão do sistema digestivo?', 'Estômago', 'Intestino', 'Pulmão', 'Fígado', 'C', 'médio', 'Biologia'),
(126, 'Quem foi o inventor da lâmpada?', 'Thomas Edison', 'Albert Einstein', 'Nikola Tesla', 'Graham Bell', 'A', 'médio', 'História'),
(127, 'Qual é a capital do Canadá?', 'Toronto', 'Montreal', 'Vancouver', 'Ottawa', 'D', 'médio', 'Geografia'),
(128, 'Quantas peças tem o jogo de xadrez?', '16', '24', '32', '40', 'C', 'médio', 'Jogos'),
(129, 'Qual destes não é um tipo de sangue humano?', 'A', 'B', 'AB', 'AO', 'D', 'médio', 'Biologia'),
(130, 'Em que século o Brasil foi descoberto?', 'XIV', 'XV', 'XVI', 'XVII', 'B', 'médio', 'História'),
(131, 'Qual é o país de origem da vodka?', 'Itália', 'França', 'Rússia', 'Alemanha', 'C', 'médio', 'Cultura'),
(132, 'Quantas notas musicais existem na escala cromática?', '7', '12', '15', '21', 'B', 'médio', 'Música'),
(133, 'Qual destes não é um planeta gasoso?', 'Júpiter', 'Saturno', 'Marte', 'Urano', 'C', 'médio', 'Ciência'),
(134, 'Quem foi o autor de "Os Lusíadas"?', 'Fernando Pessoa', 'Luís de Camões', 'Eça de Queirós', 'Machado de Assis', 'B', 'médio', 'Literatura'),
(135, 'Qual é o menor país do mundo?', 'Mônaco', 'Vaticano', 'San Marino', 'Liechtenstein', 'B', 'médio', 'Geografia'),
(136, 'Quantas casas tem o tabuleiro de damas?', '32', '64', '100', '144', 'B', 'médio', 'Jogos'),
(137, 'Qual destes não é um componente do sangue?', 'Plaquetas', 'Glóbulos vermelhos', 'Glóbulos brancos', 'Neurônios', 'D', 'médio', 'Biologia'),
(138, 'Em que ano foi lançado o primeiro iPhone?', '2005', '2007', '2010', '2012', 'B', 'médio', 'Tecnologia'),
(139, 'Qual é o idioma oficial do Brasil?', 'Espanhol', 'Inglês', 'Português', 'Francês', 'C', 'médio', 'Cultura'),
(140, 'Quantos elementos químicos a tabela periódica possui?', '92', '108', '118', '126', 'C', 'médio', 'Ciência'),
(141, 'Qual destes não é um estilo musical brasileiro?', 'Samba', 'Funk', 'Bossa Nova', 'Country', 'D', 'médio', 'Música'),
(142, 'Quem foi o primeiro homem a viajar no espaço?', 'Neil Armstrong', 'Yuri Gagarin', 'Alan Shepard', 'John Glenn', 'B', 'médio', 'História'),
(143, 'Qual é o maior lago da América do Sul?', 'Lago Titicaca', 'Lagoa dos Patos', 'Lagoa Rodrigo de Freitas', 'Lago Paranoá', 'A', 'médio', 'Geografia'),
(144, 'Quantos títulos mundiais tem a seleção brasileira de futebol?', '3', '4', '5', '6', 'C', 'médio', 'Esportes'),
(145, 'Qual destes não é um sistema do corpo humano?', 'Digestivo', 'Respiratório', 'Nervoso', 'Metálico', 'D', 'médio', 'Biologia'),
(146, 'Em que ano foi fundada a cidade de São Paulo?', '1450', '1500', '1554', '1600', 'C', 'médio', 'História'),
(147, 'Qual é o país de origem do sushi?', 'China', 'Coreia do Sul', 'Japão', 'Tailândia', 'C', 'médio', 'Cultura'),
(148, 'Quantas peças tem um dominó tradicional?', '18', '24', '28', '32', 'C', 'médio', 'Jogos'),
(149, 'Qual destes não é um tipo de rocha?', 'Ígnea', 'Sedimentar', 'Metamórfica', 'Magnética', 'D', 'médio', 'Ciência'),
(150, 'Quem pintou "A Noite Estrelada"?', 'Pablo Picasso', 'Vincent van Gogh', 'Salvador Dalí', 'Claude Monet', 'B', 'médio', 'Arte'),
(151, 'Qual é o maior animal terrestre atual?', 'Urso polar', 'Elefante africano', 'Girafa', 'Rinoceronte', 'B', 'médio', 'Biologia'),
(152, 'Quantas estrelas tem a bandeira dos EUA?', '48', '50', '52', '54', 'B', 'médio', 'Conhecimentos Gerais'),
(153, 'Qual destes não é um instrumento de cordas?', 'Violino', 'Violoncelo', 'Harpa', 'Trompete', 'D', 'médio', 'Música'),
(154, 'Em que ano terminou a Segunda Guerra Mundial?', '1939', '1943', '1945', '1950', 'C', 'médio', 'História'),
(155, 'Qual é o rio mais extenso da Europa?', 'Danúbio', 'Volga', 'Sena', 'Tâmisa', 'B', 'médio', 'Geografia'),
(156, 'Quantos jogadores tem um time de basquete em quadra?', '3', '5', '7', '9', 'B', 'médio', 'Esportes'),
(157, 'Qual destes não é um mineral?', 'Quartzo', 'Diamante', 'Ouro', 'Petróleo', 'D', 'médio', 'Ciência'),
(158, 'Quem foi o criador da teoria da relatividade?', 'Isaac Newton', 'Albert Einstein', 'Stephen Hawking', 'Galileu Galilei', 'B', 'médio', 'Ciência'),
(159, 'Qual é a capital da China?', 'Xangai', 'Hong Kong', 'Pequim', 'Cantão', 'C', 'médio', 'Geografia'),
(160, 'Quantos graus tem um círculo completo?', '90', '180', '270', '360', 'D', 'médio', 'Matemática'),
(161, 'Qual destes não é um tipo de nuvem?', 'Cúmulo', 'Estrato', 'Cirro', 'Magma', 'D', 'médio', 'Ciência'),
(162, 'Quem escreveu "Romeu e Julieta"?', 'Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain', 'B', 'médio', 'Literatura'),
(163, 'Qual é o país com maior número de ilhas?', 'Indonésia', 'Filipinas', 'Japão', 'Suécia', 'D', 'médio', 'Geografia'),
(164, 'Quantos ossos tem o crânio humano?', '6', '8', '10', '12', 'B', 'médio', 'Biologia'),
(165, 'Qual destes não é um componente do sistema solar?', 'Planetas', 'Estrelas', 'Galáxias', 'Asteroides', 'C', 'médio', 'Ciência'),
(166, 'Em que ano foi inventado o avião?', '1895', '1903', '1910', '1920', 'B', 'médio', 'História'),
(167, 'Qual é o país de origem do futebol?', 'Brasil', 'Estados Unidos', 'Inglaterra', 'Alemanha', 'C', 'médio', 'Esportes'),
(168, 'Quantas teclas tem um piano padrão?', '66', '72', '88', '96', 'C', 'médio', 'Música'),
(169, 'Qual destes não é um gás nobre?', 'Hélio', 'Neônio', 'Argônio', 'Oxigênio', 'D', 'médio', 'Ciência'),
(170, 'Quem foi o primeiro imperador do Brasil?', 'Dom Pedro I', 'Dom Pedro II', 'Dom João VI', 'Dom Miguel I', 'A', 'médio', 'História'),
(171, 'Qual é o maior arquipélago do mundo?', 'Havaí', 'Filipinas', 'Indonésia', 'Japão', 'C', 'médio', 'Geografia'),
(172, 'Quantos continentes são banhados pelo oceano Atlântico?', '3', '4', '5', '6', 'B', 'médio', 'Geografia'),
(173, 'Qual destes não é um tipo de triângulo?', 'Equilátero', 'Isósceles', 'Escaleno', 'Quadrangular', 'D', 'médio', 'Matemática'),
(174, 'Em que ano foi proclamada a República no Brasil?', '1822', '1889', '1900', '1922', 'B', 'médio', 'História'),
(175, 'Qual é o país com maior número de vulcões ativos?', 'Japão', 'Indonésia', 'Estados Unidos', 'Chile', 'B', 'médio', 'Geografia'),
(176, 'Quantos anos durou a construção da Torre Eiffel?', '1', '2', '3', '4', 'B', 'médio', 'História'),
(177, 'Qual destes não é um órgão dos sentidos?', 'Olhos', 'Ouvidos', 'Pele', 'Pulmões', 'D', 'médio', 'Biologia'),
(178, 'Quem foi o descobridor do Brasil?', 'Cristóvão Colombo', 'Pedro Álvares Cabral', 'Vasco da Gama', 'Fernão de Magalhães', 'B', 'médio', 'História'),
(179, 'Qual é o maior estado brasileiro em área?', 'Minas Gerais', 'Amazonas', 'Mato Grosso', 'Pará', 'B', 'médio', 'Geografia'),
(180, 'Quantas patas tem uma aranha?', '6', '8', '10', '12', 'B', 'médio', 'Biologia'),
(181, 'Qual destes não é um estilo arquitetônico?', 'Gótico', 'Barroco', 'Renascimento', 'Cromático', 'D', 'médio', 'Arte'),
(182, 'Em que ano foi criado o Facebook?', '2002', '2004', '2006', '2008', 'B', 'médio', 'Tecnologia'),
(183, 'Qual é o país com maior número de fusos horários?', 'Estados Unidos', 'China', 'Rússia', 'Canadá', 'C', 'médio', 'Geografia'),
(184, 'Quantas peças tem um jogo de xadrez para cada jogador?', '12', '14', '16', '18', 'C', 'médio', 'Jogos'),
(185, 'Qual destes não é um tipo de eclipse?', 'Solar', 'Lunar', 'Anular', 'Estelar', 'D', 'médio', 'Ciência'),
(186, 'Quem foi o primeiro presidente dos Estados Unidos?', 'Thomas Jefferson', 'Abraham Lincoln', 'George Washington', 'Benjamin Franklin', 'C', 'médio', 'História'),
(187, 'Qual é o maior oceano do mundo?', 'Atlântico', 'Índico', 'Pacífico', 'Ártico', 'C', 'médio', 'Geografia'),
(188, 'Quantas estrelas tem a constelação do Cruzeiro do Sul?', '4', '5', '6', '7', 'B', 'médio', 'Ciência'),
(189, 'Qual destes não é um tipo de músculo?', 'Cardíaco', 'Esquelético', 'Liso', 'Ósseo', 'D', 'médio', 'Biologia'),
(190, 'Em que ano o Brasil sediou a Copa do Mundo pela primeira vez?', '1950', '1962', '1970', '1994', 'A', 'médio', 'Esportes'),
(191, 'Qual é o país de origem da pizza?', 'França', 'Espanha', 'Itália', 'Grécia', 'C', 'médio', 'Cultura'),
(192, 'Quantos elementos tem um conjunto quádruplo?', '2', '3', '4', '5', 'C', 'médio', 'Matemática'),
(193, 'Qual destes não é um tipo de solo?', 'Arenoso', 'Argiloso', 'Humoso', 'Líquido', 'D', 'médio', 'Ciência'),
(194, 'Quem foi o autor de "1984"?', 'Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'J.R.R. Tolkien', 'B', 'médio', 'Literatura'),
(195, 'Qual é o menor estado brasileiro em área?', 'Rio de Janeiro', 'Sergipe', 'Alagoas', 'Distrito Federal', 'B', 'médio', 'Geografia'),
(196, 'Quantos lados tem um dodecágono?', '8', '10', '12', '14', 'C', 'médio', 'Matemática'),
(197, 'Qual destes não é um tipo de vento?', 'Brisa', 'Furacão', 'Tornado', 'Maré', 'D', 'médio', 'Ciência'),
(198, 'Em que ano foi assinada a Declaração de Independência dos EUA?', '1756', '1776', '1789', '1812', 'B', 'médio', 'História'),
(199, 'Qual é o país com maior número de lagos?', 'Estados Unidos', 'Rússia', 'Canadá', 'Finlândia', 'C', 'médio', 'Geografia'),
(200, 'Quantos anos tem um milênio?', '100', '500', '1000', '2000', 'C', 'médio', 'Conhecimentos Gerais');

-- Questões Difíceis (201-300)
INSERT INTO questoes_show_do_milhao VALUES
(201, 'Qual é o ponto mais profundo dos oceanos?', 'Fossa das Marianas', 'Fossa de Tonga', 'Fossa das Filipinas', 'Fossa de Porto Rico', 'A', 'difícil', 'Geografia'),
(202, 'Quem foi o primeiro filósofo a propor que a matéria era composta por átomos?', 'Aristóteles', 'Demócrito', 'Sócrates', 'Platão', 'B', 'difícil', 'Filosofia'),
(203, 'Qual é a velocidade da luz no vácuo em metros por segundo?', '299.792', '300.000', '299.792.458', '300.000.000', 'C', 'difícil', 'Física'),
(204, 'Em qual ano ocorreu o desastre nuclear de Chernobyl?', '1979', '1986', '1991', '1984', 'B', 'difícil', 'História'),
(205, 'Qual destes não é um teorema matemático famoso?', 'Teorema de Pitágoras', 'Teorema de Tales', 'Teorema de Darwin', 'Teorema de Fermat', 'C', 'difícil', 'Matemática'),
(206, 'Qual diretor venceu o Oscar por "O Poderoso Chefão Part II" e "O Irlandês"?', 'Steven Spielberg', 'Martin Scorsese', 'Francis Ford Coppola', 'Quentin Tarantino', 'C', 'difícil', 'Entretenimento'),
(207, 'Qual ator interpretou o Coringa em "Cavaleiro das Trevas" (2008)?', 'Joaquin Phoenix', 'Heath Ledger', 'Jared Leto', 'Jack Nicholson', 'B', 'difícil', 'Entretenimento'),
(208, 'Qual filme ganhou o Oscar de Melhor Filme em 1994, derrotando "A Lista de Schindler"?', 'Pulp Fiction', 'Forrest Gump', 'O Rei Leão', 'Clube da Luta', 'B', 'difícil', 'Entretenimento'),
(209, 'Qual franquia de filmes tem a maior bilheteria da história (ajustada pela inflação)?', 'Star Wars', 'Vingadores', 'James Bond', 'Harry Potter', 'A', 'difícil', 'Entretenimento'),
(210, 'Qual destes filmes NÃO foi dirigido por Stanley Kubrick?', '2001: Uma Odisseia no Espaço', 'Laranja Mecânica', 'O Iluminado', 'Tubarão', 'D', 'difícil', 'Entretenimento'),
(211, 'Qual atriz venceu o Oscar por "As Horas" (2002) e "O Diabo Veste Prada" (2006)?', 'Meryl Streep', 'Nicole Kidman', 'Cate Blanchett', 'Kate Winslet', 'B', 'difícil', 'Entretenimento'),
(212, 'Qual filme possui a famosa citação "Você não pode lidar com a verdade!"?', 'Top Gun', 'Um Sonho de Liberdade', 'Código de Honra', 'O Resgate do Soldado Ryan', 'C', 'difícil', 'Entretenimento'),
(213, 'Qual destes filmes foi totalmente rodado em plano sequência aparente?', 'Birdman', '1917', 'O Farol', 'Parasita', 'B', 'difícil', 'Entretenimento'),
(214, 'Qual ator interpretou Wolverine nos filmes dos X-Men?', 'Hugh Jackman', 'Ryan Reynolds', 'Chris Hemsworth', 'Robert Downey Jr.', 'A', 'difícil', 'Entretenimento'),
(215, 'Qual filme de animação da Disney foi o primeiro a usar CGI em 3D?', 'O Rei Leão', 'Toy Story', 'Frozen', 'Moana', 'B', 'difícil', 'Entretenimento'),
(216, 'Qual destes não é um dos "Últimos Teoremas" de Fermat?', 'Teorema do Número Primo', 'Teorema sobre Triângulos', 'Teorema da Soma de Dois Quadrados', 'Teorema do Valor Intermediário', 'D', 'difícil', 'Matemática'),
(217, 'Qual é o país com maior número de patrimônios mundiais da UNESCO?', 'França', 'China', 'Itália', 'Espanha', 'C', 'difícil', 'Cultura'),
(218, 'Quem descobriu a penicilina?', 'Marie Curie', 'Alexander Fleming', 'Louis Pasteur', 'Robert Koch', 'B', 'difícil', 'Biologia'),
(219, 'Qual é a temperatura absoluta zero em Celsius?', '-100°C', '-273°C', '-300°C', '-373°C', 'B', 'difícil', 'Física'),
(220, 'Quantos cromossomos tem uma célula humana diploide?', '23', '42', '46', '48', 'C', 'difícil', 'Biologia'),
(221, 'Qual destes não é um problema do Prêmio Millennium?', 'Hipótese de Riemann', 'Conjectura de Poincaré', 'Teorema de Fermat', 'Equações de Navier-Stokes', 'C', 'difícil', 'Matemática'),
(222, 'Em que ano foi decifrado o código genético humano?', '1985', '1995', '2001', '2003', 'D', 'difícil', 'Biologia'),
(223, 'Qual é a capital da Mongólia?', 'Astana', 'Bishkek', 'Ulan Bator', 'Dushanbe', 'C', 'difícil', 'Geografia'),
(224, 'Quem provou a conjectura de Poincaré?', 'Andrew Wiles', 'Grigori Perelman', 'Terence Tao', 'John Nash', 'B', 'difícil', 'Matemática'),
(225, 'Qual é o único metal líquido à temperatura ambiente?', 'Bromo', 'Mercúrio', 'Césio', 'Gálio', 'B', 'difícil', 'Química'),
(226, 'Quantas dimensões tem a teoria das cordas?', '5', '7', '10', '12', 'C', 'difícil', 'Física'),
(227, 'Qual destes não é um satélite de Júpiter?', 'Europa', 'Ganimedes', 'Titã', 'Calisto', 'C', 'difícil', 'Astronomia'),
(228, 'Quem foi o primeiro matemático a calcular a circunferência da Terra?', 'Aristóteles', 'Eratóstenes', 'Ptolomeu', 'Arquimedes', 'B', 'difícil', 'História'),
(229, 'Qual é a constante matemática conhecida como "proporção áurea"?', 'π', 'e', 'φ', 'γ', 'C', 'difícil', 'Matemática'),
(230, 'Em que ano foi inventado o primeiro transistor?', '1939', '1947', '1951', '1956', 'B', 'difícil', 'Tecnologia'),
(231, 'Qual é a fórmula química do ácido sulfúrico?', 'H2SO3', 'H2SO4', 'H3SO4', 'HSO4', 'B', 'difícil', 'Química'),
(232, 'Quantas partículas subatômicas fundamentais existem no Modelo Padrão?', '12', '17', '24', '31', 'B', 'difícil', 'Física'),
(233, 'Qual destes não é um dos "problemas de Hilbert"?', 'Hipótese do Contínuo', 'Existência de números transcendentes', 'Teoria dos números primos', 'Conjectura de Goldbach', 'D', 'difícil', 'Matemática'),
(234, 'Quem formulou as leis do movimento planetário?', 'Galileu Galilei', 'Isaac Newton', 'Johannes Kepler', 'Nicolau Copérnico', 'C', 'difícil', 'Astronomia'),
(235, 'Qual é o país com maior número de línguas faladas?', 'Índia', 'China', 'Nigéria', 'Papua-Nova Guiné', 'D', 'difícil', 'Geografia'),
(236, 'Quantos prêmios Nobel Marie Curie recebeu?', '1', '2', '3', '4', 'B', 'difícil', 'História'),
(237, 'Qual é a equação de Schrödinger?', 'Uma equação diferencial para ondas', 'Uma equação de campo gravitacional', 'Uma equação termodinâmica', 'Uma equação de movimento', 'A', 'difícil', 'Física'),
(238, 'Em que ano foi descoberto o bóson de Higgs?', '2008', '2010', '2012', '2015', 'C', 'difícil', 'Física'),
(239, 'Qual destes não é um tipo de quark?', 'Up', 'Down', 'Charm', 'Photon', 'D', 'difícil', 'Física'),
(240, 'Quem provou o Último Teorema de Fermat?', 'David Hilbert', 'Andrew Wiles', 'Grigori Perelman', 'Terence Tao', 'B', 'difícil', 'Matemática'),
(241, 'Qual é a capital do Butão?', 'Katmandu', 'Thimphu', 'Dhaka', 'Naypyidaw', 'B', 'difícil', 'Geografia'),
(242, 'Quantas operações fundamentais existem na computação quântica?', '1', '2', '3', '4', 'C', 'difícil', 'Tecnologia'),
(243, 'Qual destes não é um dos quatro teoremas da incompletude de Gödel?', 'Teorema da completude', 'Teorema da incompletude', 'Teorema da consistência', 'Teorema da indecidibilidade', 'A', 'difícil', 'Matemática'),
(244, 'Quem desenvolveu a teoria das supercordas?', 'Albert Einstein', 'Stephen Hawking', 'Edward Witten', 'Richard Feynman', 'C', 'difícil', 'Física'),
(245, 'Qual é o país com maior número de fusos horários?', 'Estados Unidos', 'Rússia', 'Canadá', 'França', 'B', 'difícil', 'Geografia'),
(246, 'Quantas dimensões tem a teoria M?', '5', '7', '10', '11', 'D', 'difícil', 'Física'),
(247, 'Qual destes não é um problema NP-completo?', 'Problema do caixeiro viajante', 'Problema da satisfatibilidade booleana', 'Problema da mochila', 'Problema da fatoração de números primos', 'D', 'difícil', 'Computação'),
(248, 'Quem formulou o princípio da incerteza?', 'Niels Bohr', 'Werner Heisenberg', 'Max Planck', 'Erwin Schrödinger', 'B', 'difícil', 'Física'),
(249, 'Qual é a capital de São Tomé e Príncipe?', 'Bissau', 'Malabo', 'São Tomé', 'Libreville', 'C', 'difícil', 'Geografia'),
(250, 'Quantas partículas elementares compõem um átomo de hélio?', '2', '3', '4', '5', 'B', 'difícil', 'Física'),
(251, 'Qual destes não é um dos sete problemas do Prêmio Millennium?', 'P versus NP', 'Hipótese de Riemann', 'Conjectura de Hodge', 'Teorema de Pitágoras', 'D', 'difícil', 'Matemática'),
(252, 'Quem desenvolveu a teoria dos jogos?', 'John Nash', 'John von Neumann', 'Alan Turing', 'Albert Einstein', 'B', 'difícil', 'Matemática'),
(253, 'Qual é o país com maior número de vulcões ativos?', 'Indonésia', 'Japão', 'Estados Unidos', 'Chile', 'A', 'difícil', 'Geografia'),
(254, 'Quantas constantes fundamentais existem na física?', '15', '23', '26', '31', 'C', 'difícil', 'Física'),
(255, 'Qual destes não é um dos paradoxos de Zenão?', 'Paradoxo de Aquiles e a tartaruga', 'Paradoxo do dardo', 'Paradoxo do lugar', 'Paradoxo do mentiroso', 'D', 'difícil', 'Filosofia'),
(256, 'Quem descobriu a estrutura do DNA?', 'Watson e Crick', 'Mendel e Morgan', 'Darwin e Wallace', 'Einstein e Bohr', 'A', 'difícil', 'Biologia'),
(257, 'Qual é a capital do Suriname?', 'Georgetown', 'Paramaribo', 'Cayenne', 'Bridgetown', 'B', 'difícil', 'Geografia'),
(258, 'Quantas cores são necessárias para colorir qualquer mapa plano?', '3', '4', '5', '7', 'B', 'difícil', 'Matemática'),
(259, 'Qual destes não é um dos quatro teoremas da incompletude de Gödel?', 'Teorema da completude', 'Teorema da incompletude', 'Teorema da consistência', 'Teorema da indecidibilidade', 'A', 'difícil', 'Matemática'),
(260, 'Quem desenvolveu a teoria das catástrofes?', 'René Thom', 'Benoit Mandelbrot', 'Edward Lorenz', 'Stephen Smale', 'A', 'difícil', 'Matemática'),
(261, 'Qual é o país com maior número de lagos naturais?', 'Finlândia', 'Canadá', 'Rússia', 'Estados Unidos', 'B', 'difícil', 'Geografia'),
(262, 'Quantas dimensões tem a teoria das supercordas?', '8', '9', '10', '11', 'C', 'difícil', 'Física'),
(263, 'Qual destes não é um dos problemas de Hilbert?', 'Hipótese do Contínuo', 'Existência de números transcendentes', 'Teoria dos números primos', 'Conjectura de Goldbach', 'D', 'difícil', 'Matemática'),
(264, 'Quem formulou a teoria do caos?', 'Edward Lorenz', 'Benoit Mandelbrot', 'René Thom', 'Stephen Smale', 'A', 'difícil', 'Matemática'),
(265, 'Qual é a capital de Tuvalu?', 'Suva', 'Funafuti', 'Tarawa', 'Majuro', 'B', 'difícil', 'Geografia'),
(266, 'Quantas partículas fundamentais existem no Modelo Padrão?', '12', '17', '24', '31', 'B', 'difícil', 'Física'),
(267, 'Qual destes não é um dos quatro teoremas da incompletude de Gödel?', 'Teorema da completude', 'Teorema da incompletude', 'Teorema da consistência', 'Teorema da indecidibilidade', 'A', 'difícil', 'Matemática'),
(268, 'Quem desenvolveu a teoria das supercordas?', 'Albert Einstein', 'Stephen Hawking', 'Edward Witten', 'Richard Feynman', 'C', 'difícil', 'Física'),
(269, 'Qual é o país com maior número de fusos horários?', 'Estados Unidos', 'Rússia', 'Canadá', 'França', 'B', 'difícil', 'Geografia'),
(270, 'Quantas dimensões tem a teoria M?', '5', '7', '10', '11', 'D', 'difícil', 'Física'),
(271, 'Qual destes não é um problema NP-completo?', 'Problema do caixeiro viajante', 'Problema da satisfatibilidade booleana', 'Problema da mochila', 'Problema da fatoração de números primos', 'D', 'difícil', 'Computação'),
(272, 'Quem formulou o princípio da incerteza?', 'Niels Bohr', 'Werner Heisenberg', 'Max Planck', 'Erwin Schrödinger', 'B', 'difícil', 'Física'),
(273, 'Qual é a capital de São Tomé e Príncipe?', 'Bissau', 'Malabo', 'São Tomé', 'Libreville', 'C', 'difícil', 'Geografia'),
(274, 'Quantas partículas elementares compõem um átomo de hélio?', '2', '3', '4', '5', 'B', 'difícil', 'Física'),
(275, 'Qual destes não é um dos sete problemas do Prêmio Millennium?', 'P versus NP', 'Hipótese de Riemann', 'Conjectura de Hodge', 'Teorema de Pitágoras', 'D', 'difícil', 'Matemática'),
(276, 'Quem desenvolveu a teoria dos jogos?', 'John Nash', 'John von Neumann', 'Alan Turing', 'Albert Einstein', 'B', 'difícil', 'Matemática'),
(277, 'Qual é o país com maior número de vulcões ativos?', 'Indonésia', 'Japão', 'Estados Unidos', 'Chile', 'A', 'difícil', 'Geografia'),
(278, 'Quantas constantes fundamentais existem na física?', '15', '23', '26', '31', 'C', 'difícil', 'Física'),
(279, 'Qual destes não é um dos paradoxos de Zenão?', 'Paradoxo de Aquiles e a tartaruga', 'Paradoxo do dardo', 'Paradoxo do lugar', 'Paradoxo do mentiroso', 'D', 'difícil', 'Filosofia'),
(280, 'Quem descobriu a estrutura do DNA?', 'Watson e Crick', 'Mendel e Morgan', 'Darwin e Wallace', 'Einstein e Bohr', 'A', 'difícil', 'Biologia'),
(281, 'Qual é a capital do Suriname?', 'Georgetown', 'Paramaribo', 'Cayenne', 'Bridgetown', 'B', 'difícil', 'Geografia'),
(282, 'Quantas cores são necessárias para colorir qualquer mapa plano?', '3', '4', '5', '7', 'B', 'difícil', 'Matemática'),
(283, 'Qual destes não é um dos quatro teoremas da incompletude de Gödel?', 'Teorema da completude', 'Teorema da incompletude', 'Teorema da consistência', 'Teorema da indecidibilidade', 'A', 'difícil', 'Matemática'),
(284, 'Quem desenvolveu a teoria das catástrofes?', 'René Thom', 'Benoit Mandelbrot', 'Edward Lorenz', 'Stephen Smale', 'A', 'difícil', 'Matemática'),
(285, 'Qual é o país com maior número de lagos naturais?', 'Finlândia', 'Canadá', 'Rússia', 'Estados Unidos', 'B', 'difícil', 'Geografia'),
(286, 'Quantas dimensões tem a teoria das supercordas?', '8', '9', '10', '11', 'C', 'difícil', 'Física'),
(287, 'Qual destes não é um dos problemas de Hilbert?', 'Hipótese do Contínuo', 'Existência de números transcendentes', 'Teoria dos números primos', 'Conjectura de Goldbach', 'D', 'difícil', 'Matemática'),
(288, 'Quem formulou a teoria do caos?', 'Edward Lorenz', 'Benoit Mandelbrot', 'René Thom', 'Stephen Smale', 'A', 'difícil', 'Matemática'),
(289, 'Qual é a capital de Tuvalu?', 'Suva', 'Funafuti', 'Tarawa', 'Majuro', 'B', 'difícil', 'Geografia'),
(290, 'Quantas partículas fundamentais existem no Modelo Padrão?', '12', '17', '24', '31', 'B', 'difícil', 'Física'),
(291, 'Qual destes não é um dos quatro teoremas da incompletude de Gödel?', 'Teorema da completude', 'Teorema da incompletude', 'Teorema da consistência', 'Teorema da indecidibilidade', 'A', 'difícil', 'Matemática'),
(292, 'Quem desenvolveu a teoria das supercordas?', 'Albert Einstein', 'Stephen Hawking', 'Edward Witten', 'Richard Feynman', 'C', 'difícil', 'Física'),
(293, 'Qual é o país com maior número de fusos horários?', 'Estados Unidos', 'Rússia', 'Canadá', 'França', 'B', 'difícil', 'Geografia'),
(294, 'Quantas dimensões tem a teoria M?', '5', '7', '10', '11', 'D', 'difícil', 'Física'),
(295, 'Qual destes não é um problema NP-completo?', 'Problema do caixeiro viajante', 'Problema da satisfatibilidade booleana', 'Problema da mochila', 'Problema da fatoração de números primos', 'D', 'difícil', 'Computação'),
(296, 'Quem formulou o princípio da incerteza?', 'Niels Bohr', 'Werner Heisenberg', 'Max Planck', 'Erwin Schrödinger', 'B', 'difícil', 'Física'),
(297, 'Qual é a capital de São Tomé e Príncipe?', 'Bissau', 'Malabo', 'São Tomé', 'Libreville', 'C', 'difícil', 'Geografia'),
(298, 'Quantas partículas elementares compõem um átomo de hélio?', '2', '3', '4', '5', 'B', 'difícil', 'Física'),
(299, 'Qual destes não é um dos sete problemas do Prêmio Millennium?', 'P versus NP', 'Hipótese de Riemann', 'Conjectura de Hodge', 'Teorema de Pitágoras', 'D', 'difícil', 'Matemática'),
(300, 'Quem desenvolveu a teoria dos jogos?', 'John Nash', 'John von Neumann', 'Alan Turing', 'Albert Einstein', 'B', 'difícil', 'Matemática');